BTCK_LTC#/Controllers/PostsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BTCK_LTC_.Models;
using Microsoft.Extensions.Hosting;
using Microsoft.AspNetCore.Authorization;
using System.IdentityModel.Tokens.Jwt;
using System.Security.Claims;
using X.PagedList;
using System.ComponentModel.Design;

namespace BTCK_LTC_.Controllers
{
    public class PostsController : Controller
    {
        private readonly QuanLyBaiDangCongTyContext _context;
        private readonly IWebHostEnvironment _hostEnvironment;
		private readonly IConfiguration _configuration;

		public PostsController(QuanLyBaiDangCongTyContext context, IWebHostEnvironment hostEnvironment, IConfiguration configuration)
        {
            _context = context;
            _hostEnvironment = hostEnvironment;
			_configuration = configuration;
		}

		// GET: Posts
		public async Task<IActionResult> Index(string searchdocs, string PostDate, string CategoryId, int? pageNumber)
        {
			//check role
			var claims = GetClaims();
			if (claims == null)
			{
				return RedirectToAction("Login", "Account");
			}
			if (!claims.Any(c => c.Type == "role" && c.Value == "Post"))
			{
				return Forbid();
			}

            var EmployeeId = Convert.ToInt32(HttpContext.Session.GetString("ID"));

            IQueryable<Post> quanLyBaiDangCongTyContext = _context.Posts.Where(p => p.EmployeeId == EmployeeId).Include(p => p.Category).Include(p => p.Employee);

            if (!string.IsNullOrEmpty(searchdocs))
            {
                quanLyBaiDangCongTyContext = quanLyBaiDangCongTyContext.Where(p => p.Title.Contains(searchdocs));
            }

            if (!string.IsNullOrEmpty(CategoryId))
            {
                quanLyBaiDangCongTyContext = quanLyBaiDangCongTyContext.Where(p => p.CategoryId == Convert.ToInt32(CategoryId));
            }

            if (PostDate == "1" || PostDate == null)
            {
                quanLyBaiDangCongTyContext = quanLyBaiDangCongTyContext.OrderByDescending(p => p.PostDate);
            }
            else
            {
                quanLyBaiDangCongTyContext = quanLyBaiDangCongTyContext.OrderBy(p => p.PostDate);
            }

			int pageSize = Convert.ToInt32(_configuration["PageList:PageSize"]);
			int currentPage = pageNumber ?? 1;

			ViewData["CategoryIdList"] = new SelectList(_context.Categories, "Id", "Name");
            ViewData["PostDate"] = PostDate;
			ViewData["CurrentSearchDocs"] = searchdocs;
			ViewData["CurrentCategoryId"] = CategoryId;
			return View(await quanLyBaiDangCongTyContext.ToPagedListAsync(currentPage, pageSize));
        }

        // GET: Posts/Details/5
        public async Task<IActionResult> Details(int? id)
        {
			//check role
			var claims = GetClaims();
			if (claims == null)
			{
				return RedirectToAction("Login", "Account");
			}
			if (!claims.Any(c => c.Type == "role" && c.Value == "Post"))
			{
				return Forbid();
			}

			if (id == null)
            {
                return NotFound();
            }

            var post = await _context.Posts
                .Include(p => p.Category)
                .Include(p => p.Employee)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (post == null)
            {
                return NotFound();
            }

            var CategoriesId = _context.Posts.FirstOrDefault(p => p.Id == id).CategoryId;

            ViewData["CategoryId"] = CategoriesId;

            return View(post);
        }

        // GET: Posts/Create
        public IActionResult CreateThongBao()
        {
			//check role
			var claims = GetClaims();
			if (claims == null)
			{
				return RedirectToAction("Login", "Account");
			}
			if (!claims.Any(c => c.Type == "role" && c.Value == "Post"))
			{
				return Forbid();
			}

            var EmployeeId = Convert.ToInt32(HttpContext.Session.GetString("ID"));
            var CategoriesId = _context.Categories.FirstOrDefault(c => c.Name == "Thông báo").Id;

            ViewData["CategoryId"] = CategoriesId;
            ViewData["EmployeeId"] = EmployeeId;
            return View();
        }

        // POST: Posts/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateThongBao([Bind("Id,Title,Content,Thumbnail,Date,PostDate,EmployeeId,CategoryId")] Post post, IFormFile? ThumbnailFile)
        {
            if (ModelState.IsValid)
            {
                if (ThumbnailFile != null)
                {
                    string uploadsFolder = Path.Combine(_hostEnvironment.WebRootPath, "thumbnails");
                    string uniqueFileName = Guid.NewGuid().ToString() + "_" + ThumbnailFile.FileName;
                    string filePath = Path.Combine(uploadsFolder, uniqueFileName);
                    using (var fileStream = new FileStream(filePath, FileMode.Create))
                    {
                        await ThumbnailFile.CopyToAsync(fileStream);
                    }
                    post.Thumbnail = uniqueFileName;
                }

                _context.Add(post);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }

            var EmployeeId = Convert.ToInt32(HttpContext.Session.GetString("ID"));
            var CategoriesId = _context.Categories.FirstOrDefault(c => c.Name == "Thông báo").Id;

            ViewData["CategoryId"] = CategoriesId;
            ViewData["EmployeeId"] = EmployeeId;
            return View(post);
        }

        // GET: Posts/Create
        public IActionResult CreateLichTrinh()
        {
            //check role
            var claims = GetClaims();
            if (claims == null)
            {
                return RedirectToAction("Login", "Account");
            }
            if (!claims.Any(c => c.Type == "role" && c.Value == "Post"))
            {
                return Forbid();
            }

            var EmployeeId = Convert.ToInt32(HttpContext.Session.GetString("ID"));
            var CategoriesId = _context.Categories.FirstOrDefault(c => c.Name == "Lịch trình").Id;

            ViewData["CategoryId"] = CategoriesId;
            ViewData["EmployeeId"] = EmployeeId;
            return View();
        }

        // POST: Posts/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateLichTrinh([Bind("Id,Title,Content,Thumbnail,Date,PostDate,EmployeeId,CategoryId")] Post post, IFormFile? ThumbnailFile)
        {
            if (ModelState.IsValid)
            {
                if (ThumbnailFile != null)
                {
                    string uploadsFolder = Path.Combine(_hostEnvironment.WebRootPath, "thumbnails");
                    string uniqueFileName = Guid.NewGuid().ToString() + "_" + ThumbnailFile.FileName;
                    string filePath = Path.Combine(uploadsFolder, uniqueFileName);
                    using (var fileStream = new FileStream(filePath, FileMode.Create))
                    {
                        await ThumbnailFile.CopyToAsync(fileStream);
                    }
                    post.Thumbnail = uniqueFileName;
                }

                _context.Add(post);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }

            var EmployeeId = Convert.ToInt32(HttpContext.Session.GetString("ID"));
            var CategoriesId = _context.Categories.FirstOrDefault(c => c.Name == "Lịch trình").Id;

            ViewData["CategoryId"] = CategoriesId;
            ViewData["EmployeeId"] = EmployeeId;
            return View(post);
        }

        // GET: Posts/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
			//check role
			var claims = GetClaims();
			if (claims == null)
			{
				return RedirectToAction("Login", "Account");
			}
			if (!claims.Any(c => c.Type == "role" && c.Value == "Post"))
			{
				return Forbid();
			}

			if (id == null)
            {
                return NotFound();
            }

            var post = await _context.Posts.FindAsync(id);
            if (post == null)
            {
                return NotFound();
            }

            var EmployeeId = Convert.ToInt32(HttpContext.Session.GetString("ID"));
            var CategoriesId = _context.Posts.FirstOrDefault(p => p.Id == id).CategoryId;

            ViewData["CategoryId"] = CategoriesId;
            ViewData["EmployeeId"] = EmployeeId;
            return View(post);
        }

        // POST: Posts/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Title,Content,Thumbnail,Date,PostDate,EmployeeId,CategoryId")] Post post, IFormFile? ThumbnailFile)
        {
            if (id != post.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    if (ThumbnailFile != null)
                    {
                        string uploadsFolder = Path.Combine(_hostEnvironment.WebRootPath, "thumbnails");
                        string uniqueFileName = Guid.NewGuid().ToString() + "_" + ThumbnailFile.FileName;
                        string filePath = Path.Combine(uploadsFolder, uniqueFileName);

BTCK_LTC#/Controllers/RolesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BTCK_LTC_.Models;
using System.IdentityModel.Tokens.Jwt;
using System.Security.Claims;
using X.PagedList;
using System.ComponentModel.Design;

namespace BTCK_LTC_.Controllers
{
    public class RolesController : Controller
    {
        private readonly QuanLyBaiDangCongTyContext _context;
		private readonly IConfiguration _configuration;

		public RolesController(QuanLyBaiDangCongTyContext context, IConfiguration configuration)
        {
            _context = context;
			_configuration = configuration;
		}

        // GET: Roles
        public async Task<IActionResult> Index(string searchdocs, int? pageNumber)
        {
			//check role
			var claims = GetClaims();
			if (claims == null)
			{
				return RedirectToAction("Login", "Account");
			}
			if (!claims.Any(c => c.Type == "role" && c.Value == "Manage"))
			{
				return Forbid();
			}

            IQueryable<Role> RolesContext = _context.Roles;

            if (!string.IsNullOrEmpty(searchdocs))
            {
                RolesContext = RolesContext.Where(r => r.Name.Contains(searchdocs));
            }

			RolesContext = RolesContext.OrderBy(r => r.Id);

			int pageSize = Convert.ToInt32(_configuration["PageList:PageSize"]);
			int currentPage = pageNumber ?? 1;

			ViewData["CurrentSearchDocs"] = searchdocs;
			return View(await RolesContext.ToPagedListAsync(currentPage, pageSize));
        }

        // GET: Roles/Details/5
        public async Task<IActionResult> Details(int? id)
        {
			//check role
			var claims = GetClaims();
			if (claims == null)
			{
				return RedirectToAction("Login", "Account");
			}
			if (!claims.Any(c => c.Type == "role" && c.Value == "Manage"))
			{
				return Forbid();
			}

			if (id == null)
            {
                return NotFound();
            }

            var role = await _context.Roles
                .FirstOrDefaultAsync(m => m.Id == id);
            if (role == null)
            {
                return NotFound();
            }

            return View(role);
        }

        // GET: Roles/Create
        public IActionResult Create()
        {
			//check role
			var claims = GetClaims();
			if (claims == null)
			{
				return RedirectToAction("Login", "Account");
			}
			if (!claims.Any(c => c.Type == "role" && c.Value == "Manage"))
			{
				return Forbid();
			}

			return View();
        }

        // POST: Roles/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Post,Manage")] Role role)
        {
            if (ModelState.IsValid)
            {
                _context.Add(role);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(role);
        }

        // GET: Roles/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
			//check role
			var claims = GetClaims();
			if (claims == null)
			{
				return RedirectToAction("Login", "Account");
			}
			if (!claims.Any(c => c.Type == "role" && c.Value == "Manage"))
			{
				return Forbid();
			}

			if (id == null)
            {
                return NotFound();
            }

            var role = await _context.Roles.FindAsync(id);
            if (role == null)
            {
                return NotFound();
            }
            return View(role);
        }

        // POST: Roles/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Post,Manage")] Role role)
        {
            if (id != role.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(role);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!RoleExists(role.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(role);
        }

        // GET: Roles/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
			//check role
			var claims = GetClaims();
			if (claims == null)
			{
				return RedirectToAction("Login", "Account");
			}
			if (!claims.Any(c => c.Type == "role" && c.Value == "Manage"))
			{
				return Forbid();
			}

			if (id == null)
            {
                return NotFound();
            }

            var role = await _context.Roles
                .FirstOrDefaultAsync(m => m.Id == id);
            if (role == null)
            {
                return NotFound();
            }

            return View(role);
        }

        // POST: Roles/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var role = await _context.Roles.FindAsync(id);
            if (role != null)
            {
                _context.Roles.Remove(role);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool RoleExists(int id)
        {
            return _context.Roles.Any(e => e.Id == id);
        }

		private IEnumerable<Claim> GetClaims()
		{
			var token = HttpContext.Session.GetString("JWToken");
			if (string.IsNullOrEmpty(token))
			{
				return null;
			}

			var handler = new JwtSecurityTokenHandler();
			var jsonToken = handler.ReadToken(token) as JwtSecurityToken;
			var claims = jsonToken.Claims;

			return claims;
		}
	}
}

BTCK_LTC#/Views/Shared/_Layout.cshtml
@using System.IdentityModel.Tokens.Jwt
@{
	var token = Context.Session.GetString("JWToken");
	int id = Convert.ToInt32(Context.Session.GetString("ID"));
	var name = Context.Session.GetString("Name");
	var avatar = Context.Session.GetString("Avatar");

	bool post = false,manage = false;

	if (!string.IsNullOrEmpty(token))
	{
		var handler = new JwtSecurityTokenHandler();
		var jsonToken = handler.ReadToken(token) as JwtSecurityToken;
		if (jsonToken != null)
		{
			var claims = jsonToken.Claims;
			if (claims.Any(c => c.Type == "role" && c.Value == "Post")){
				post = true;
			}
			if (claims.Any(c => c.Type == "role" && c.Value == "Manage"))
			{
				manage = true;
			}
		}
		
	}
}
<!DOCTYPE html>
<html lang="en"> 
<head>
	<title>Portal - Bootstrap 5 Admin Dashboard Template For Developers</title>

	<!-- Meta -->
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">

	<meta name="description" content="Portal - Bootstrap 5 Admin Dashboard Template For Developers">
	<meta name="author" content="Xiaoying Riley at 3rd Wave Media">    
	<link rel="shortcut icon" href="favicon.ico"> 

	<!-- FontAwesome JS-->
	<script defer src="~/plugins/fontawesome/js/all.min.js"></script>

	<!-- App CSS -->  
	<link id="theme-style" rel="stylesheet" href="~/css/portal.css">

</head> 

<body class="app">   	
	<header class="app-header fixed-top">	   	            
		<div class="app-header-inner">  
			<div class="container-fluid py-2">
				<div class="app-header-content"> 
					<div class="row justify-content-between align-items-center">

					<div class="col-auto">
						<a id="sidepanel-toggler" class="sidepanel-toggler d-inline-block d-xl-none" href="#">
							<svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" viewBox="0 0 30 30" role="img"><title>Menu</title><path stroke="currentColor" stroke-linecap="round" stroke-miterlimit="10" stroke-width="2" d="M4 7h22M4 15h22M4 23h22"></path></svg>
						</a>
					</div><!--//col-->
					<div class="search-mobile-trigger d-sm-none col">
						<i class="search-mobile-trigger-icon fa-solid fa-magnifying-glass"></i>
					</div><!--//col-->
					<div class="app-search-box col">
						<form class="app-search-form">   
							<input type="text" placeholder="Search..." name="search" class="form-control search-input">
							<button type="submit" class="btn search-btn btn-primary" value="Search"><i class="fa-solid fa-magnifying-glass"></i></button> 
						</form>
					</div><!--//app-search-box-->

					<div class="app-utilities col-auto">
							
						@if (token == null)
						{
							<div class="app-utility-item">
								<a asp-area="" asp-controller="Account" asp-action="Login" style="margin: 0px 5px 0px 0px">Đăng nhập</a>
							</div>
							
						}else
						{
							<div class="app-utility-item app-user-dropdown dropdown">
								<a class="dropdown-toggle" id="user-dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-expanded="false"><img src="~/avatars/@avatar" style="border-radius:9999px;"></a>
								<ul class="dropdown-menu" aria-labelledby="user-dropdown-toggle">
									<li><a class="dropdown-item" asp-area="" asp-controller="Account" asp-action="Index" asp-route-id="@id">Tài khoản</a></li>
									<li><hr class="dropdown-divider"></li>
									<li><a class="dropdown-item" asp-area="" asp-controller="Account" asp-action="Logout">Đăng xuất</a></li>
								</ul>
							</div><!--//app-user-dropdown-->	
						}

					</div><!--//app-utilities-->
				</div><!--//row-->
				</div><!--//app-header-content-->
			</div><!--//container-fluid-->
		</div><!--//app-header-inner-->
		<div id="app-sidepanel" class="app-sidepanel"> 
			<div id="sidepanel-drop" class="sidepanel-drop"></div>
			<div class="sidepanel-inner d-flex flex-column">
				<a href="#" id="sidepanel-close" class="sidepanel-close d-xl-none">&times;</a>
				<div class="app-branding">
					<a class="app-logo" asp-controller="Home" asp-action="Index"><img class="logo-icon me-2" src="~/images/app-logo.svg" alt="logo"><span class="logo-text">PORTAL</span></a>

				</div><!--//app-branding-->  

				<nav id="app-nav-main" class="app-nav app-nav-main flex-grow-1">
					<ul class="app-menu list-unstyled accordion" id="menu-accordion">
						<li class="nav-item">
							<!--//Bootstrap Icons: https://icons.getbootstrap.com/ -->
							<a class="nav-link" asp-controller="Home" asp-action="Index">
								<span class="nav-icon">
								<svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-house-door" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
		  <path fill-rule="evenodd" d="M7.646 1.146a.5.5 0 0 1 .708 0l6 6a.5.5 0 0 1 .146.354v7a.5.5 0 0 1-.5.5H9.5a.5.5 0 0 1-.5-.5v-4H7v4a.5.5 0 0 1-.5.5H2a.5.5 0 0 1-.5-.5v-7a.5.5 0 0 1 .146-.354l6-6zM2.5 7.707V14H6v-4a.5.5 0 0 1 .5-.5h3a.5.5 0 0 1 .5.5v4h3.5V7.707L8 2.207l-5.5 5.5z"/>
		  <path fill-rule="evenodd" d="M13 2.5V6l-2-2V2.5a.5.5 0 0 1 .5-.5h1a.5.5 0 0 1 .5.5z"/>
		</svg>
								 </span>
								 <span class="nav-link-text">Trang chủ</span>
							</a><!--//nav-link-->
						</li><!--//nav-item-->

						@if (post)
						{
							<li class="nav-item">
								<!--//Bootstrap Icons: https://icons.getbootstrap.com/ -->
								<a class="nav-link" asp-area="" asp-controller="Posts" asp-action="Index">
									<span class="nav-icon">
										<svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-card-list" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
											<path fill-rule="evenodd" d="M14.5 3h-13a.5.5 0 0 0-.5.5v9a.5.5 0 0 0 .5.5h13a.5.5 0 0 0 .5-.5v-9a.5.5 0 0 0-.5-.5zm-13-1A1.5 1.5 0 0 0 0 3.5v9A1.5 1.5 0 0 0 1.5 14h13a1.5 1.5 0 0 0 1.5-1.5v-9A1.5 1.5 0 0 0 14.5 2h-13z"/>
											<path fill-rule="evenodd" d="M5 8a.5.5 0 0 1 .5-.5h7a.5.5 0 0 1 0 1h-7A.5.5 0 0 1 5 8zm0-2.5a.5.5 0 0 1 .5-.5h7a.5.5 0 0 1 0 1h-7a.5.5 0 0 1-.5-.5zm0 5a.5.5 0 0 1 .5-.5h7a.5.5 0 0 1 0 1h-7a.5.5 0 0 1-.5-.5z"/>
											<circle cx="3.5" cy="5.5" r=".5"/>
											<circle cx="3.5" cy="8" r=".5"/>
											<circle cx="3.5" cy="10.5" r=".5"/>
										</svg>
									</span>
									<span class="nav-link-text">Bài đăng</span>
								</a><!--//nav-link-->
							</li><!--//nav-item-->
						}
						@if (manage)
						{
							<li class="nav-item has-submenu">
								<!--//Bootstrap Icons: https://icons.getbootstrap.com/ -->
								<a class="nav-link submenu-toggle" href="#" data-bs-toggle="collapse" data-bs-target="#submenu-1" aria-expanded="false" aria-controls="submenu-1">
									<span class="nav-icon">
										<!--//Bootstrap Icons: https://icons.getbootstrap.com/ -->
										<svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-files" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
											<path fill-rule="evenodd" d="M4 2h7a2 2 0 0 1 2 2v10a2 2 0 0 1-2 2H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2zm0 1a1 1 0 0 0-1 1v10a1 1 0 0 0 1 1h7a1 1 0 0 0 1-1V4a1 1 0 0 0-1-1H4z"/>
											<path d="M6 0h7a2 2 0 0 1 2 2v10a2 2 0 0 1-2 2v-1a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1H6a1 1 0 0 0-1 1H4a2 2 0 0 1 2-2z"/>
										</svg>
									</span>
									<span class="nav-link-text">Quản lý</span>
									<span class="submenu-arrow">
										<svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-chevron-down" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
											<path fill-rule="evenodd" d="M1.646 4.646a.5.5 0 0 1 .708 0L8 10.293l5.646-5.647a.5.5 0 0 1 .708.708l-6 6a.5.5 0 0 1-.708 0l-6-6a.5.5 0 0 1 0-.708z"/>
										</svg>
									</span><!--//submenu-arrow-->
								</a><!--//nav-link-->
								<div id="submenu-1" class="collapse submenu submenu-1" data-bs-parent="#menu-accordion">
									<ul class="submenu-list list-unstyled">
										<li class="submenu-item"><a class="submenu-link" asp-area="" asp-controller="Companies" asp-action="Index">Công Ty</a></li>
										<li class="submenu-item"><a class="submenu-link" asp-area="" asp-controller="Departments" asp-action="Index">Phòng ban</a></li>
										<li class="submenu-item"><a class="submenu-link" asp-area="" asp-controller="Roles" asp-action="Index">Chức vụ</a></li>
										<li class="submenu-item"><a class="submenu-link" asp-area="" asp-controller="Categories" asp-action="Index">Danh mục</a></li>
										<li class="submenu-item"><a class="submenu-link" asp-area="" asp-controller="Employees" asp-action="Index">Nhân viên</a></li>
									</ul>
								</div>
							</li><!--//nav-item-->
						}
						
		    
					</ul><!--//app-menu-->
				</nav><!--//app-nav-->
				

			</div><!--//sidepanel-inner-->
		</div><!--//app-sidepanel-->
	</header><!--//app-header-->

	<div class="app-wrapper">

		<div class="app-content pt-3 p-md-3 p-lg-4">
			<div class="container-xl">

				@RenderBody()

			</div><!--//container-fluid-->
		</div><!--//app-content-->

		<footer class="app-footer">
			<div class="container text-center py-3">
				 <!--/* This template is free as long as you keep the footer attribution link. If you'd like to use the template without the attribution link, you can buy the commercial license via our website: themes.3rdwavemedia.com Thank you for your support. :) */-->
			<small class="copyright">Designed with <span class="sr-only">love</span><i class="fas fa-heart" style="color: #fb866a;"></i> by <a class="app-link" href="http://themes.3rdwavemedia.com" target="_blank">Xiaoying Riley</a> for developers</small>

			</div>
		</footer><!--//app-footer-->

	</div><!--//app-wrapper-->    					


	<!-- Javascript -->          
	<script src="~/plugins/popper.min.js"></script>
	<script src="~/plugins/bootstrap/js/bootstrap.min.js"></script>  

	<!-- Charts JS -->
	<script src="~/plugins/chart.js/chart.min.js"></script> 
	<script src="~/js/index-charts.js"></script> 

	<!-- Page Specific JS -->
	<script src="~/js/app.js"></script> 

	<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

	<script>
	$(document).ready(function() {
		// Lấy URL của trang hiện tại
		var fullUrl = window.location.href;

		// Tạo đối tượng URL từ URL hiện tại
		var url = new URL(fullUrl);

		// Lấy phần pathname
		var relativePath = url.pathname;

		console.log(relativePath);
		// Loại bỏ lớp 'active' từ tất cả các mục submenu
		$('.submenu-link[href="'+ relativePath +'"]').closest('.submenu').addClass('show');
		$('.nav-link[href="'+ relativePath +'"]').addClass('active');
		$('.submenu-link[href="'+ relativePath +'"]').closest('.nav-item').find('.nav-link').attr('aria-expanded', 'true');
		$('.submenu-link[href="'+ relativePath +'"]').closest('.nav-item').find('.nav-link').addClass('active');
		$('.submenu-link[href="'+ relativePath +'"]').addClass('active');
	});
	</script>
	@RenderSection("Scripts",required: false)
</body>
</html> 